version: '3.7'
services:
  openldap:
    image: finishertech/openldap:withdata
    build: .
    environment:
      LDAP_ADMIN_PASSWORD: 'You are an Ironman!'
      LDAP_BASE_DN: dc=finisher,dc=tech
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  phpldapadmin:
    image: osixia/phpldapadmin
    ports:
      - 8080:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config:
